[package]
name = "cypto-related-experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20.6"
pem = "1.1.0"
rcgen = "0.9.3"
ran = "1.0.1"